"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

total = 0
prev = 1
num = 1

while(num < 4000000):
    fib = num + prev
    if (fib % 2 == 0):
        total += fib
    prev = num
    num = fib
    
print("Sum of even Fibonacci numbers below 4 million:\n" + str(total))